### ISSUE TITLE
Out-of-memory exception when loading SOSD benchmark datasets

### ISSUE THREAD

**Issue by Bachfischer** [Jiacheng-WU/lipp#1]
Hi,

there appears to be an out-of-memory exception when loading the SOSD benchmark datasets. 

Example dataset: https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/JGVF9A/EATHF7&version=10.0

I'm running my experiments with 32 GB of RAM and have been able to successfully load the datasets with ALEX, STX-BTree and Dynamic-PGM, so the available memory should be sufficient.

Code to reproduce the issue:

```C++
#include <vector>
#include <fstream>
#include <iostream>
#include "lipp.h"

template<typename Key>
std::vector<Key> load_data(const std::string &filename) {
    using key_type = Key;

    /* Open file. */
    std::ifstream in(filename, std::ios::binary);
    if (!in.is_open())
        exit(EXIT_FAILURE);

    /* Read number of keys. */
    uint64_t n_keys;
    in.read(reinterpret_cast<char*>(&n_keys), sizeof(uint64_t));

    /* Initialize vector. */
    std::vector<key_type> data;
    data.resize(n_keys);

    /* Read keys. */
    in.read(reinterpret_cast<char*>(data.data()), n_keys * sizeof(key_type));
    in.close();

    return data;
}

int main(int argc, char *argv[])
{
    /* Load keys. */
    auto keys = load_data<uint64_t>("data/wiki_ts_200M_uint64");

    std::vector<std::pair<uint64_t, uint64_t>>  key_value_pairs;
    key_value_pairs.reserve(keys.size());

    for (auto& key : keys) {
      key_value_pairs.push_back(std::make_pair(key, 100));
    }
    std::cout << "Keys loaded" << std::endl;

    /* Build LIPP. */
    LIPP<uint64_t, uint64_t> lipp;
    lipp.bulk_load(key_value_pairs.data(), key_value_pairs.size());
    std::cout << "LIPP index built succesfully" << std::endl;
}
```

Output:

```
bachfischer@learned-indexes-benchmark:~/lipp$ ./build/experiments 
Keys loaded
Killed
```

**Comment by Bachfischer** [comment]
Follow-up:

Might not be related, but when I modify the sample code `example_bulk_load.cpp` to load 1,000,000 keys (instead of 100,000), I get the following error:

```
bachfischer@learned-indexes-benchmark:~/lipp$ ./build/example_bulk_load
RT_ASSERT Error at /home/bachfischer/lipp/src/core/lipp.h:371, `key1 < key2`
```

Code to reproduce:

```C++
#include <lipp.h>
#include <iostream>
#include <vector>
#include <cassert>

using namespace std;

int main()
{
    LIPP<int, int> lipp;

    // prepare data
    vector<pair<int, int>> data;
    for (int i = 0; i < 1000000; i ++) {
        data.push_back({i, i % 127});
    }

    // bulk load
    lipp.bulk_load(data.data(), data.size());

    // normal insert
    lipp.insert(-100, 5);
    lipp.insert(187688, 4);

    // verify LIPP data structure
    lipp.verify();

    // test correctness
    assert(lipp.at(-100) == 5);
    assert(lipp.at(187688) == 4);
    for (int i = 0; i < 100000; i ++) {
        assert(lipp.exists(i));
        assert(lipp.at(i) == (i % 127));
    }

    cout << "bolk load success" << endl;

    return 0;
}
```

Code is also available here: [https://github.com/Bachfischer/lipp)](https://github.com/Bachfischer/lipp)

Thanks!

**Comment by Jiacheng-WU** [comment]
Thanks for your interests! 
For the first issue, I guess you may forget to sort the keys in the datasets before you bulk load them.
For the second one, the assertion is triggered at lipp.insert(187688, 4) since the key 187688 is contained in the range [0, 1000000-1] after your modification. Change 187688 with a larger key can solve this issues.
Please first refer to the implementation when you encounter some wired cases.

**Comment by Bachfischer** [comment]
Hi Jiacheng,

many thanks for getting back to me! 

For the first issue, I made sure that the dataset is ordered and tried with both the [fb_200M_uint64](https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/JGVF9A/EATHF7&version=10.0) and [wiki_ts_200M_uint64](https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/JGVF9A/SVN8PI&version=10.0) datasets. Both of them get killed with out-of-memory error.

Have you been able to successfully bulk load large datasets with ~200M keys? 

Best,
Matthias

**Comment by Jiacheng-WU** [comment]
Though it is wired since it runs correctly on our datasets. However, It
might be possible, and we have used more memory since we reserve enough gap
for future insertions.

You could pass fewer numbers for the LIPP constructors to make BUILD_GAP_CNT
small, such as 2 or 3. But it will incur some overheads and may hurt the
performance.

In the future work, we will provide a constexpr function, which will accept
the number of keys and return the gap count during the adjustment period.

You could adjust this function to balance the time and space trade-off.

Sincerely,
Jiacheng

**Comment by Jiacheng-WU** [comment]
Follow-up

So if you are not urgent to finish some papers, I suggest you could wait
for about a week, and we would fix this issue and
add some reminders on the customized points of this constexpr function.

Sincerely,
Jiacheng

**Comment by Bachfischer** [comment]
Hi Jiacheng,

not urgent at all! 

I'll keep an eye on your repository and will try again once you have had the time to push some fixes. 

Looking forward!

Matthias

**Comment by Jiacheng-WU** [comment]
Sounds good!
