### ISSUE TITLE
RT_ASSERT Error happened when inserting

### ISSUE THREAD

**Issue by bysoul** [Jiacheng-WU/lipp#13]
Hi Jiacheng, 

Thanks for sharing your excellent work. We want to evaluate several kinds of Learned Index. When we inserted 100,000,000 kv pairs into LIPP, RT_ASSERT Error happened. But when 80,000,000 kv pairs were inserted, it worked fine. So is there some limits of total amount of kv pairs?
```
int main(){
    LIPP<int , int> lipp{};
    for(int i=0;i<100000000;i++){
        lipp.insert(std::pair<int , int>(i,i));
    }
}
```
Output
`
RT_ASSERT Error at ./index/lipp/lipp.h:805, `path_size < MAX_DEPTH`
`

**Comment by Jiacheng-WU** [comment]
Hi Dear, 

I guess you could just modify the value of MAX_DEPTH (in line 799) with a larger value (>128).
We just it to static create a node array to avoid the cost of dynamic allocations.
It seems with a larger number of kv pairs, the size of the path is larger than MAX_DEPTH we expected.

Sincerely,
Jiacheng

**Comment by bysoul** [comment]
Hi Jiacheng,
It works fine. Thanks again for sharing your excellent work.
